modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/GLDYM/ExpandedStorage-KOTS/issues"
license = "MIT"

[[mods]]
modId = "expandedstorage"
version = "10.3.2"
displayName = "Expanded Storage KOTS"
authors = "Polaris_Light"
logoFile = "icon.png"
displayURL = "https://curseforge.com/minecraft/mc-mods/expanded-storage-kots"
description = "KOTS Fork of Expanded Storage, adding more storage blocks and features."

[[dependencies.expandedstorage]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedstorage]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "NONE"
side = "BOTH"
